version: "3.9"  # optional since v1.27.0
services:
  node-red:
    image: nodered/node-red:2.2.2
    restart: always
    network_mode: "host"
    volumes:
      - "$HOME/node-red:/data"
    user: "0"
    ports:
      - "1880:1880"
  dataloader:
    image: dev:dataloader-build
    environment:
            - UDEV=1
    restart: always
    runtime: nvidia
    network_mode: "host"
    privileged: true
    devices:
    - "/dev:/dev"
    ports:
      - "5550:5550"
  detection:
    image: dev:detection-build
    restart: always
    runtime: nvidia
    network_mode: "host"
    ports:
      - "5560:5560"
    
